### ISSUE TITLE
Add head collection for each player

### ISSUE THREAD

**Issue by PancakeTAS** [PancakeTAS/Daybreak#4]
Every player kill will add the victims head into a head collection which will be viewable through a command. Players will lose all of their heads on death. ~~The top 3 killers will have their head collections leaked at midnight on server reset in the discord webhook.~~

**Comment by p2r3** [comment]
+1

On a server like this, a leaderboard system of any kind just makes sense. If I'm getting this right, the proposal is to count heads only for the active day? That's probably for the best, otherwise we'll have stacked players hogging the top 3 constantly.

_(or, you know, implement a valueless point system like epochtal)_

**Comment by PancakeTAS** [comment]
I do like the idea of having a global head collection actually, one that preserves between resets. We would need a way to overthrow stacked players if we did that as you said. Here's my idea for a global head collection:

3 random players (let's just say I) will get a golden head, silver head and bronze head representing my rank on the server. If I get killed my lowest level head will be given to the killer. This way lower level players won't even get targeted as much because they aren't worth anything and players with most gear who will have those 3 heads placing them in first second and third place (publicly announced of course).
My guess is that this system will naturally have the top 3 players be the most stacked. This does however still have two problems:
- What happens if multiple players team up to kill one stacked player, who will get the head?
- *I forgot the other problem I'm sure I will remember it in a second*

The other head collection which holds actual player heads should be reset on death, not every day. If we do implement the above system then the player head collection wouldn't even be used for ranking. Then again I'm not sure if this is the right idea.

Thoughts?

**Comment by p2r3** [comment]
Give... players...head. Mhm, noted!

I'm a bit confused on what the final system would look like now. Are these tangible heads, or just a statistic? Where is this information kept and displayed? I like the idea of these heads being a general motivator to hunt rich players, though I am lost on how this indicates a global position.

**Comment by PancakeTAS** [comment]
I'll try explaining this from the beginning.
When I say player head, that's just the visual representation of what I'm actually talking about. The "player head" is nothing more than a string in a list on the server, that can be viewed in a player inventory using a command.
My idea is that we give out 3 strings which are first, second and third place represented as gold silver and bronze heads. Players can then fight for those heads and whoever kills a player holding one, will steal it from them. After a few days the heads will be spread across 3 players and the global top 3 leaderboard will *hopefully* be spread out to the strongest and best pvper on the server.

The *other* head collection I had in mind is still just a string in a list, except that it's in a different list and resets when the player dies. An example: I kill 3 players, I get their heads and have them in my collection. Now I got killed and those 3 heads will be lost. Not stolen or anything, just lost.

**Comment by PancakeTAS** [comment]
Ranked heads have been renamed to crowns and will be tracked in #5
